spring:
  datasource:
    url: "jdbc:mysql://localhost:3306/kotlin?serverTimezone=Asia/Seoul&characterEncoding=UTF-8"
    username: "root"
    password: "root"

  jpa:
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    defer-datasource-initialization: true
    hibernate.ddl-auto: update
    show-sql: true
    open-in-view: false
    properties:
      hibernate.format_sql: true
      hibernate.default_batch_fetch_size: 100
  sql.init.mode: always

jwt:
  secret-key: ${SECRET_KEY}
  access-exp-time: 3600000   # 1시간
  refresh-exp-time: 604800000   # 7일

springdoc:
  api-docs:
    enabled: true
  swagger-ui:
    enabled: true
    tagsSorter: alpha
    operations-sorter: alpha
    display-request-duration: true
  version: '1.0'
